/**
 * Hand-maintained data-quality notes for cross-country comparability and
 * contested / self-reported series. Not generated by fetch-gdp.mjs.
 */

export type MeasureClass =
  | "nominal-gdp"
  | "nominal-gva"
  | "chain-volume"
  | "other";

export type SourceQuality = {
  sourceKey: "bea" | "statcan" | "abs" | "eurostat" | "worldbank" | "oecd";
  measureClass: MeasureClass;
  /** Short label shown in UI badges */
  badge: string;
  /** Whether country totals are roughly comparable as nominal USD levels */
  levelComparableToNominalUsd: boolean;
  summary: string;
};

/** Measure semantics by primary industry source. */
export const SOURCE_QUALITY: Record<string, SourceQuality> = {
  bea: {
    sourceKey: "bea",
    measureClass: "nominal-gdp",
    badge: "Nominal GDP",
    levelComparableToNominalUsd: true,
    summary:
      "BEA GDP by industry in current dollars (SAAR). Closest to nominal USD GDP.",
  },
  worldbank: {
    sourceKey: "worldbank",
    measureClass: "nominal-gdp",
    badge: "Nominal GDP",
    levelComparableToNominalUsd: true,
    summary:
      "World Bank current-USD GDP and sector value added (compiled from national accounts).",
  },
  eurostat: {
    sourceKey: "eurostat",
    measureClass: "nominal-gva",
    badge: "GVA (not GDP)",
    levelComparableToNominalUsd: false,
    summary:
      "Eurostat gross value added (B1G) at current prices. GVA excludes taxes less subsidies on products, so levels sit below market-price GDP.",
  },
  oecd: {
    sourceKey: "oecd",
    measureClass: "nominal-gva",
    badge: "GVA (not GDP)",
    levelComparableToNominalUsd: false,
    summary:
      "OECD Table 6 gross value added at current prices. Comparable to Eurostat GVA, not to market-price GDP.",
  },
  statcan: {
    sourceKey: "statcan",
    measureClass: "chain-volume",
    badge: "Volume ≠ $",
    levelComparableToNominalUsd: false,
    summary:
      "Statistics Canada GDP at basic prices, chained 2017 dollars (volume). Converting with market FX does not produce nominal USD GDP — levels and GDP/capita are not apples-to-apples with USA/China.",
  },
  abs: {
    sourceKey: "abs",
    measureClass: "chain-volume",
    badge: "Volume ≠ $",
    levelComparableToNominalUsd: false,
    summary:
      "ABS chain-volume GVA (quarterly SA ×4). Not a current-price dollar measure — levels and GDP/capita are not comparable to nominal USD GDP.",
  },
};

export type AltEstimate = {
  label: string;
  value: string;
  note: string;
  url: string;
  yearLabel: string;
};

export type ContestedField = {
  field: "population" | "gdp" | "gdpPerCapita" | "ageStructure";
  severity: "high" | "medium";
  title: string;
  why: string;
  officialLabel: string;
  alternatives: AltEstimate[];
  counterpoints?: { label: string; note: string; url: string }[];
};

export type CountryQuality = {
  code: string;
  /** Non-comparable measure vs nominal USD GDP peers */
  measureWarning?: boolean;
  contested?: ContestedField[];
};

/**
 * Contested / self-reported series. Figures are published estimates from named
 * sources — not invented adjustments applied to the chart totals.
 */
export const COUNTRY_QUALITY: Record<string, CountryQuality> = {
  USA: { code: "USA" },
  CHN: {
    code: "CHN",
    contested: [
      {
        field: "population",
        severity: "high",
        title: "Official population is contested",
        why: "World Bank population for China is compiled from National Bureau of Statistics releases. Independent demographers argue births and totals have been systematically overstated for funding and planning incentives; others dispute the size of any gap.",
        officialLabel: "Official / World Bank (NBS-based)",
        alternatives: [
          {
            label: "Yi Fuxian (UW–Madison)",
            value: "~1.28 billion",
            yearLabel: "vs ~1.41B official around 2020–23",
            note: "Estimates China’s population roughly 100–130 million below official census / NBS totals; argues overstatement since the 1990s.",
            url: "https://www.reuters.com/world/china/researcher-questions-chinas-population-data-says-it-may-be-lower-2021-12-03/",
          },
          {
            label: "Yi Fuxian (2023–24 commentary)",
            value: "~130 million below official",
            yearLabel: "on ~1.41B official 2023",
            note: "Maintains the true total is about 130 million smaller than the official 1.41 billion figure reported for 2023.",
            url: "https://www.newsweek.com/china-hiding-population-secret-1926834",
          },
        ],
        counterpoints: [
          {
            label: "Wang Feng (UC Irvine)",
            note: "Argues Chinese and UN analyses have not found evidence of 100+ million over-reporting across post-2000 censuses.",
            url: "https://www.socsci.uci.edu/newsevents/news/2024/2024-07-17-wang-feng-newsweek.php",
          },
        ],
      },
      {
        field: "gdp",
        severity: "high",
        title: "Official GDP growth is widely doubted",
        why: "Chart GDP for China comes from World Bank current-USD series that track NBS national accounts. Independent trackers argue official growth systematically exceeds real activity — especially after the property downturn — so the USD level may also be overstated.",
        officialLabel: "Official NBS (via World Bank)",
        alternatives: [
          {
            label: "Rhodium Group",
            value: "2024 growth ~2.4–2.8%",
            yearLabel: "vs official ~5%",
            note: "Estimates 2024 GDP growth at 2.4–2.8%, well below official claims near 5%.",
            url: "https://rhg.com/research/after-the-fall-chinas-economy-in-2025/",
          },
          {
            label: "Rhodium Group",
            value: "2023 growth ~1.5%",
            yearLabel: "vs official 5.2%",
            note: "Baseline 2023 growth estimate of about 1.5% versus official 5.2%.",
            url: "https://rhg.com/wp-content/uploads/2024/02/Through-the-Looking-Glass-Chinas-2023-GDP-and-the-Year-Ahead-1.pdf",
          },
          {
            label: "Rhodium / cited Chinese economists",
            value: "~10% smaller economy (~$1.7T)",
            yearLabel: "cumulative overstatement",
            note: "If growth was overstated by ~3 pp for three years, implied GDP level is around 10% (~$1.7 trillion) below official data.",
            url: "https://rhg.com/research/after-the-fall-chinas-economy-in-2025/",
          },
        ],
      },
      {
        field: "gdpPerCapita",
        severity: "high",
        title: "GDP per capita inherits both biases",
        why: "Per capita divides the official-linked GDP total by the official-linked population. If GDP is overstated and/or population is overstated, the ratio can move either way — treat it as an official-series construct, not an independently verified living standard.",
        officialLabel: "Official GDP ÷ official population",
        alternatives: [
          {
            label: "Implication (Yi population)",
            value: "Higher per capita if pop lower",
            yearLabel: "illustrative",
            note: "A ~100–130M smaller population would raise per capita for any given GDP total; Rhodium-style lower GDP pulls the other way.",
            url: "https://www.reuters.com/world/china/researcher-questions-chinas-population-data-says-it-may-be-lower-2021-12-03/",
          },
        ],
      },
      {
        field: "ageStructure",
        severity: "medium",
        title: "Age shares also track official NBS inputs",
        why: "World Bank 0–14 and 65+ shares for China are built from the same national statistical system. If births were overstated, the young-age share may be overstated too.",
        officialLabel: "World Bank (NBS-based)",
        alternatives: [
          {
            label: "Yi Fuxian fertility critique",
            value: "Lower fertility / fewer births",
            yearLabel: "long-run",
            note: "Argues published birth and fertility rates were inflated; that would compress the under-18 cohort relative to official age structure.",
            url: "https://www.reuters.com/world/china/researcher-questions-chinas-population-data-says-it-may-be-lower-2021-12-03/",
          },
        ],
      },
    ],
  },
  DEU: { code: "DEU", measureWarning: true },
  JPN: { code: "JPN", measureWarning: true },
  IND: { code: "IND" },
  GBR: { code: "GBR", measureWarning: true },
  FRA: { code: "FRA", measureWarning: true },
  ITA: { code: "ITA", measureWarning: true },
  CAN: { code: "CAN", measureWarning: true },
  AUS: { code: "AUS", measureWarning: true },
  RUS: { code: "RUS" },
  BRA: { code: "BRA" },
  ESP: { code: "ESP", measureWarning: true },
  KOR: { code: "KOR" },
  MEX: { code: "MEX", measureWarning: true },
  TUR: { code: "TUR", measureWarning: true },
  IDN: { code: "IDN" },
  NLD: { code: "NLD", measureWarning: true },
  SAU: { code: "SAU" },
  CHE: { code: "CHE", measureWarning: true },
  POL: { code: "POL", measureWarning: true },
  BEL: { code: "BEL", measureWarning: true },
  IRL: { code: "IRL", measureWarning: true },
  ARG: { code: "ARG" },
  SWE: { code: "SWE", measureWarning: true },
  NOR: { code: "NOR", measureWarning: true },
  THA: { code: "THA" },
  ARE: { code: "ARE" },
  SGP: { code: "SGP" },
  NGA: { code: "NGA" },
  ZAF: { code: "ZAF" },
  AUT: { code: "AUT", measureWarning: true },
  ISR: { code: "ISR" },
  EGY: { code: "EGY" },
  VNM: { code: "VNM" },
  BGD: { code: "BGD" },
};

export function qualityForCountry(
  code: string,
  sourceKey: string | undefined,
): {
  source: SourceQuality | null;
  country: CountryQuality;
} {
  const source = sourceKey ? (SOURCE_QUALITY[sourceKey] ?? null) : null;
  const country = COUNTRY_QUALITY[code] ?? { code };
  return {
    source,
    country: {
      ...country,
      measureWarning:
        country.measureWarning ??
        (source ? !source.levelComparableToNominalUsd : false),
    },
  };
}

export function contestedFor(
  code: string,
  field: ContestedField["field"],
): ContestedField | undefined {
  return COUNTRY_QUALITY[code]?.contested?.find((c) => c.field === field);
}
